name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean build
      run: make clean || true
    
#    - name: Build (Debug)
#      run: make BUILD_TYPE=debug
    
#    - name: Run watchdog (Debug test)
#      run: |
#        timeout --preserve-status 600s ./processWatchdog > debug_watchdog_stdout.log 2> debug_watchdog_stderr.log
#        cat debug_watchdog_stdout.log
#        cat debug_watchdog_stderr.log
    
#    - name: Clean
#      run: make clean
    
    - name: Build (Release)
      run: make BUILD_TYPE=release
    
    - name: Run watchdog (Release test)
      run: |
        echo "Running processWatchdog..."
        timeout --signal=SIGUSR1 --preserve-status 600s ./processWatchdog > release_watchdog_stdout.log 2> release_watchdog_stderr.log
        echo "Standard Output:"
        cat watchdog_stdout.log
        echo "Standard Error:"
        cat watchdog_stderr.log
