name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean build
      run: make clean || true
    
    - name: Build (Release)
      run: make BUILD_TYPE=release
    
    - name: Run watchdog
      run: |
        echo "Running processWatchdog..."
        ./monitor.sh 2 1 5 3 ./processWatchdog > release_watchdog_stdout.log 2> release_watchdog_stderr.log
        echo "Standard Output:"
        cat release_watchdog_stdout.log
        echo "Standard Error:"
        cat release_watchdog_stderr.log
